routes/web.php
<?php
Auth::routes(['register' => false]);
Route::middleware(['auth','admin'])->group(function () {
    // Home

    // Route::get('/admin/home', 'HomeController@index')->name('home');
    // Route::get('/home', 'HomeController@index');
    // User CRUD
    Route::resource('/admin/user','Admin\UserController');

    // Super User CRUD
    Route::resource('/admin/superuser','Admin\SuperUser');

    // Map
    Route::resource('map','Admin\GoogleMap');

    // Dashboard
    Route::get('admin','Admin\Dashboard@index')->name('home');;

    // Lamppost Routing
    Route::get('admin/lamppost','Admin\Lamppost@home');
    Route::get('admin/lamppost/map','Admin\Lamppost@map');
    Route::get('admin/lamppost/cameras','Admin\Lamppost@cameras');
    Route::get('admin/lamppost/aqi','Admin\Lamppost@aqi');
    Route::get('admin/lamppost/lights','Admin\Lamppost@lights');

    // Programs CRUD
    Route::resource('admin/lamppost/programs', 'Admin\Program');
    Route::get('admin/lamppost/programs/send/{id}', 'Admin\Program@send');
    Route::get('admin/lamppost/programs/info/{id}', 'Admin\Program@info');
    Route::get('admin/lamppost/programs/query/{id}', 'Admin\Program@query');
    Route::post('admin/lamppost/programs/make', 'Admin\Program@make');

    // Emergency Routing
    Route::resource('admin/lamppost/emergency', 'Admin\Emergency');
    Route::get('admin/lamppost/emergency_call', 'Admin\Emergency@call');
    Route::get('admin/lamppost/emergency_info', 'Admin\Emergency@info');

    // Group
    Route::resource('admin/lamppost/group', 'Admin\group');
    Route::resource('admin/lamppost/medias', 'Admin\Media');
    Route::post('admin/lamppost/media', 'Admin\Media@media');
    Route::resource('admin/lamppost/settings', 'Admin\Setting');

    // Display
    Route::get('admin/lamppost/displays','Admin\Display@index');
    Route::post('admin/lamppost/displays/buffer','Admin\Display@buffer')->name('buffer');
    Route::post('admin/lamppost/displays/upload','Admin\Display@upload')->name('display.upload');

    // Log Activity
    Route::resource('admin/lamppost/logs','Admin\ActivityLog');

    // Video stream test
    Route::get('video/streaming','Log\DebugLog@index');

    // configure the  inividual device setup
    Route::get('admin/setup','Admin\Setup@index');

    // Crud for smart pole list
    Route::resource('admin/pole','Admin\SmartPole');

    // camera list for rightsidebar
    Route::post('lamppost/cameralist','Admin\Camera@camera_list')->name('camera.list');
    Route::post('lamppost/camerastream','Admin\Camera@stream')->name('camera.stream');


});



Route::middleware(['auth','client'])->group(function () {
    Route::get('/', 'Client\Dashboard@index');

    // Map
    Route::resource('map','Admin\GoogleMap');

    // Lamppost Routing
    Route::get('lamppost','Client\Lamppost@home');
    Route::get('lamppost/map','Client\Lamppost@map');
    Route::get('lamppost/cameras','Client\Lamppost@cameras');
    Route::get('lamppost/aqi','Client\Lamppost@aqi');
    Route::get('lamppost/lights','Client\Lamppost@lights');

    // Programs CRUD
    Route::resource('lamppost/program', 'Client\Program');
    Route::get('lamppost/programs/send/{id}', 'Client\Program@send');
    Route::get('lamppost/programs/info/{id}', 'Client\Program@info');
    Route::get('lamppost/programs/query/{id}', 'Client\Program@query');
    Route::post('lamppost/programs/make', 'Client\Program@make');

    // Emergency Routing
    Route::resource('lamppost/emergency', 'Client\Emergency');
    Route::get('lamppost/emergency_call', 'Client\Emergency@call');
    Route::get('lamppost/emergency_info', 'Client\Emergency@info');

    // Group
    Route::resource('lamppost/group', 'Client\group');
    Route::resource('lamppost/media', 'Client\Media');
    Route::post('lamppost/media', 'Client\Media@media');
    Route::resource('lamppost/settings', 'Client\Setting');

    // Display
    Route::get('lamppost/displays','Client\Display@index');

    // Log Activity
    Route::resource('lamppost/log','Client\ActivityLog');


});
Route::get('store','Admin\Camera@store')->name('camera.store');

// Route::resource('client','Payment\Client');
Route::get('{slug}','HomeController@slug');

app/Models/Log.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Log extends Model
{
    protected $table = 'logs';
    protected $fillable = [
        'subject', 'url', 'method', 'ip', 'agent', 'user_name'
    ];
}

app/Http/Controllers/Log/DebugLog.php
<?php

namespace App\Http\Controllers\Log;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DebugLog extends Controller
{
    public function index(Request $request)
    {
        return response()->json(['success' => true, 'code' => 200, 'streaming_url' => 'rtsp://admin:admin@123@192.168.1.108/cam/realmonitor?channel=1&subtype=1']);
    //    return view('admin.lamppost.camera.index');
    }
}

resources/views/log/index.blade.php
@extends('admin.include.layout')
@section('css')
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<section class="content">
<div class="container-fluid"><br>
    <p class="mt-1">
        <div class="row">
        <div class="col-md-6 offset-md-3 mb-2">
            <div class="row">
                <div class="col-md-4">
                    <input type="text" name="from_date" id="from_date" class="form-control" placeholder="From Date"  />
                </div>
                <div class="col-md-4">
                    <input type="text" name="to_date" id="to_date" class="form-control" placeholder="To Date"  readonly/>
                </div>
                <div class="col-md-4">
                    <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                    <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
                </div>
            </div>
        </div>

    </div>
    </p>
    <table class="table table-sm table-bordered data-table table-hover ">
        <thead class="bg-dark">
            <tr class="text-center">
                <th>#</th>
                <th>User</th>
                <th>Subject</th>
                <th>Method</th>
                <th width="70px" class="text-center">IP</th>
                <th>Agent</th>
                <th width="100px" class="text-center">Created At</th>
                <th width="100px" class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
</section>
@endsection
@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script type="text/javascript">



  $(function () {
    var options={
        uiLibrary: 'bootstrap4',
        format: 'yyyy-mm-dd hh:mm:ss',
        todayHighlight: true,
        autoclose: true,
      };
    $('#from_date').datetimepicker(options);

    $('#from_date').change(function(){
        var from = $(this).val();
        if(from !== ''){
            $('#to_date').datetimepicker(options);
           $('#to_date').removeAttr('readonly');
        }
        else{
            $('#to_date').attr('readonly',true);
        }
    })
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('logs.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex',orderable: false, searchable: false},
            {data: 'user_name', name: 'user_name'},
            {data: 'subjects', name: 'subjects'},
            {data: 'url_method', name: 'url_method'},
            {data: 'ip', name: 'ip'},
            {data: 'agents', name: 'agents'},
            {data: 'new_time', name: 'new_time'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });

    $(document).on('click','#delete-btn',function(){
        var $button = $(this);
        var id = $(this).attr('data-id');

         bootbox.confirm({
            title: '<i class="fa fa-trash fa-lg"></i>Delete Record?',
            message: "Do you want to delete it or not.",
            buttons: {
                cancel: {
                    label: '<i class="fa fa-times"></i> Cancel'
                },
                confirm: {
                    label: '<i class="fa fa-check"></i> Confirm'
                }
            },
            callback: function (result) {
                if(result)
                {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url : "{{url('admin/lamppost/logs')}}"+"/"+id,
                        type: "DELETE",
                        data : {},
                        success: function(data, textStatus, jqXHR)
                        {
                            console.info(data);
                            console.log(textStatus);
                            console.log(jqXHR);
                            if(textStatus == 'success'){
                                table.row( $button.parents('tr') ).remove().draw();
                                toastr.success('Success', data.message,{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                            }
                            else{
                                toastr.error('Error', data.message,{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                            }
                        },
                        error: function (jqXHR, textStatus, errorThrown)
                        {
                            console.info(jqXHR);
                            console.log(textStatus);
                            console.log(errorThrown);
                            toastr.error('Error', 'Internal error occur.',{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                        }
                    });
                }
            }
        });
    })

    $(document).on('click','#view-btn',function(){
       var id = $(this).attr('data-id');
       $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        $.ajax({
            url : "{{url('admin/lamppost/logs')}}"+"/"+id,
            type: "GET",
            data : {},
            success: function(data, textStatus, jqXHR)
            {
                console.log(data);
                if(textStatus == 'success'){
                    var dialog = bootbox.dialog({
                        title: '<div style="align-text:center;">Log Detail</div>',
                        message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>'
                    });

                    dialog.init(function(){
                        setTimeout(function(){
                            dialog.find('.bootbox-body').html(`
                            <div class="form-group row">
                                <label for="staticName" class="col-sm-4 col-form-label">User Name</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticName" value="`+data.data.user_name+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticSubject" class="col-sm-4 col-form-label">Subject</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticSubject" value="`+data.data.subject+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticUrl" class="col-sm-4 col-form-label">Url</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticUrl" value="`+data.data.url+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticMethod" class="col-sm-4 col-form-label">Email</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticMethod" value="`+data.data.method+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticIp" class="col-sm-4 col-form-label">IP</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticIp" value="`+data.data.ip+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticAgent" class="col-sm-4 col-form-label">Agent</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticAgent" value="`+data.data.agent+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticCreate" class="col-sm-4 col-form-label">Created At</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext" id="staticCreate" value="`+data.data.created_at+`">
                                </div>
                            </div>`);
                        }, 500);
                    });
                }
                else{

                }
            },
            error: function (jqXHR, textStatus, errorThrown)
            {}
        });
    });

  });
</script>
@endsection