routes/web.php
<?php
Auth::routes(['register' => false]);
Route::middleware(['auth','admin'])->group(function () {
    // Home

    // Route::get('/admin/home', 'HomeController@index')->name('home');
    // Route::get('/home', 'HomeController@index');
    // User CRUD
    Route::resource('/admin/user','Admin\UserController');

    // Super User CRUD
    Route::resource('/admin/superuser','Admin\SuperUser');

    // Map
    Route::resource('map','Admin\GoogleMap');

    // Dashboard
    Route::get('admin','Admin\Dashboard@index')->name('home');;

    // Lamppost Routing
    Route::get('admin/lamppost','Admin\Lamppost@home');
    Route::get('admin/lamppost/map','Admin\Lamppost@map');
    Route::get('admin/lamppost/cameras','Admin\Lamppost@cameras');
    Route::get('admin/lamppost/aqi','Admin\Lamppost@aqi');
    Route::get('admin/lamppost/lights','Admin\Lamppost@lights');

    // Programs CRUD
    Route::resource('admin/lamppost/programs', 'Admin\Program');
    Route::get('admin/lamppost/programs/send/{id}', 'Admin\Program@send');
    Route::get('admin/lamppost/programs/info/{id}', 'Admin\Program@info');
    Route::get('admin/lamppost/programs/query/{id}', 'Admin\Program@query');
    Route::post('admin/lamppost/programs/make', 'Admin\Program@make');

    // Emergency Routing
    Route::resource('admin/lamppost/emergency', 'Admin\Emergency');
    Route::get('admin/lamppost/emergency_call', 'Admin\Emergency@call');
    Route::get('admin/lamppost/emergency_info', 'Admin\Emergency@info');

    // Group
    Route::resource('admin/lamppost/group', 'Admin\group');
    Route::resource('admin/lamppost/medias', 'Admin\Media');
    Route::post('admin/lamppost/media', 'Admin\Media@media');
    Route::resource('admin/lamppost/settings', 'Admin\Setting');

    // Display
    Route::get('admin/lamppost/displays','Admin\Display@index');
    Route::post('admin/lamppost/displays/buffer','Admin\Display@buffer')->name('buffer');
    Route::post('admin/lamppost/displays/upload','Admin\Display@upload')->name('display.upload');

    // Log Activity
    Route::resource('admin/lamppost/logs','Admin\ActivityLog');

    // Video stream test
    Route::get('video/streaming','Log\DebugLog@index');

    // configure the  inividual device setup
    Route::get('admin/setup','Admin\Setup@index');

    // Crud for smart pole list
    Route::resource('admin/pole','Admin\SmartPole');

    // camera list for rightsidebar
    Route::post('lamppost/cameralist','Admin\Camera@camera_list')->name('camera.list');
    Route::post('lamppost/camerastream','Admin\Camera@stream')->name('camera.stream');


});



Route::middleware(['auth','client'])->group(function () {
    Route::get('/', 'Client\Dashboard@index');

    // Map
    Route::resource('map','Admin\GoogleMap');

    // Lamppost Routing
    Route::get('lamppost','Client\Lamppost@home');
    Route::get('lamppost/map','Client\Lamppost@map');
    Route::get('lamppost/cameras','Client\Lamppost@cameras');
    Route::get('lamppost/aqi','Client\Lamppost@aqi');
    Route::get('lamppost/lights','Client\Lamppost@lights');

    // Programs CRUD
    Route::resource('lamppost/program', 'Client\Program');
    Route::get('lamppost/programs/send/{id}', 'Client\Program@send');
    Route::get('lamppost/programs/info/{id}', 'Client\Program@info');
    Route::get('lamppost/programs/query/{id}', 'Client\Program@query');
    Route::post('lamppost/programs/make', 'Client\Program@make');

    // Emergency Routing
    Route::resource('lamppost/emergency', 'Client\Emergency');
    Route::get('lamppost/emergency_call', 'Client\Emergency@call');
    Route::get('lamppost/emergency_info', 'Client\Emergency@info');

    // Group
    Route::resource('lamppost/group', 'Client\group');
    Route::resource('lamppost/media', 'Client\Media');
    Route::post('lamppost/media', 'Client\Media@media');
    Route::resource('lamppost/settings', 'Client\Setting');

    // Display
    Route::get('lamppost/displays','Client\Display@index');

    // Log Activity
    Route::resource('lamppost/log','Client\ActivityLog');


});
Route::get('store','Admin\Camera@store')->name('camera.store');

// Route::resource('client','Payment\Client');
Route::get('{slug}','HomeController@slug');

app/Models/Pole.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pole extends Model
{
    protected $table = 'poles';

    public function camera()
    {
        return $this->belongsTo('App\Models\Camera','id', 'pole_id');
    }

    public function sensor()
    {
        return $this->belongsTo('App\Models\Sensor', 'id', 'pole_id');
    }

    public function screen()
    {
        return $this->belongsTo('App\Models\Screen', 'id', 'pole_id');
    }
}

app/Http/Controllers/Client/ActivityLog.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivityLog extends Controller
{
    //
}

app/Http/Controllers/Client/Dashboard.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Dashboard extends Controller
{
    public function index(Request $request)
    {
        return view('client.dashboard.index');
    }
}

app/Http/Controllers/Client/Display.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Display extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/Emergency.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Emergency extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/Group.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Group extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/Lamppost.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Log as LogActivity;

class Lamppost extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    // Lamppad Status
    public function home(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost Home view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.home');
    }

    public function map(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost map view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.map');
    }

    public function cameras(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost Camera view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.cameras');
    }

    public function aqi(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost aqi view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.aqi');
    }

    public function lights(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost Light view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.lights');
    }

    public function programs(Request $request)
    {
        $log = [];
    	$log['subject'] = 'Lamppost Programs view';
    	$log['url'] = $request->fullUrl();
    	$log['method'] = $request->method();
    	$log['ip'] = $request->ip();
    	$log['agent'] = $request->header('user-agent');
        $log['user_name'] = auth()->check() ? auth()->user()->name : 'Admin user';

        LogActivity::create($log);
        return view('client.lamppost.programs');
    }
}

app/Http/Controllers/Client/Map.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Map extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/Media.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Media extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/Program.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Program extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/client/pole/index.blade.php
@extends('admin.include.layout')
@section('css')
<script>
    $(function(){
      @if(\Session::has('pole_create'))
          toastr.success('Success', "{{ \Session::get('pole_create') }}",{
          showMethod: 'fadeIn',
          showDuration: 300,
          showEasing: 'swing',
          hideMethod: 'fadeOut',
          hideDuration: 1000,
          hideEasing: 'swing',
          extendedTimeOut: 1000,
          positionClass: 'toast-top-center',
          timeOut: 3000,
          escapeHtml: false,
          newestOnTop: true,
          preventDuplicates: false,
          progressBar: true
          });
      @endif
      @if(\Session::has('pole_edit'))
          toastr.success('Success', "{{ \Session::get('pole_edit') }}",{
          showMethod: 'fadeIn',
          showDuration: 300,
          showEasing: 'swing',
          hideMethod: 'fadeOut',
          hideDuration: 1000,
          hideEasing: 'swing',
          extendedTimeOut: 1000,
          positionClass: 'toast-top-center',
          timeOut: 3000,
          escapeHtml: false,
          newestOnTop: true,
          preventDuplicates: false,
          progressBar: true
          });
      @endif
    });
  </script>
@endsection
@section('content')
<section class="content">
<div class="container">
    <h1>All Smart Pole List</h1>
    <p class="float-right"><a href="{{route('pole.create')}}" class="btn btn-primary"> <i class="fa fa-plus"></i>&nbsp;create pole</a></p>
    <table class="table table-bordered data-table">
        <thead class="bg-dark text-center">
            <tr>
                <th style="width:70px">#</th>
                <th>Name</th>
                <th>Ip</th>
                <th>Location</th>
                <th>Link Users</th>
                <th width="100px" class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
</section>
@endsection
@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
<script type="text/javascript">

  $(function () {

    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('pole.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'names', name: 'names'},
            {data: 'ips', name: 'ips'},
            {data: 'locations', name: 'locations'},
            {data: 'link_users', name: 'link_users'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });

    $(document).on('click','#delete-btn',function(){
        var id = $(this).attr('data-id');
         bootbox.confirm({
            title: '<i class="fa fa-trash fa-lg"></i>Delete Record?',
            message: "Do you want to delete it or not.",
            buttons: {
                cancel: {
                    label: '<i class="fa fa-times"></i> Cancel'
                },
                confirm: {
                    label: '<i class="fa fa-check"></i> Confirm'
                }
            },
            callback: function (result) {
                if(result)
                {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url : "{{url('admin/pole')}}"+"/"+id,
                        type: "DELETE",
                        data : {},
                        success: function(data, textStatus, jqXHR)
                        {
                            console.info(data);
                            console.log(textStatus);
                            console.log(jqXHR);
                            if(textStatus == 'success'){
                                toastr.success('Success', data.message,{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                            }
                            else{
                                toastr.error('Error', data.message,{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                            }
                        },
                        error: function (jqXHR, textStatus, errorThrown)
                        {
                            console.info(jqXHR);
                            console.log(textStatus);
                            console.log(errorThrown);
                            toastr.error('Error', 'Internal error occur.',{
                                showMethod: 'fadeIn',
                                showDuration: 300,
                                showEasing: 'swing',
                                hideMethod: 'fadeOut',
                                hideDuration: 1000,
                                hideEasing: 'swing',
                                extendedTimeOut: 1000,
                                positionClass: 'toast-top-center',
                                timeOut: 3000,
                                escapeHtml: false,
                                newestOnTop: true,
                                preventDuplicates: false,
                                progressBar: true
                                });
                        }
                    });
                }
            }
        });
    })

    $(document).on('click','#view-btn',function(){
       var id = $(this).attr('data-id');
       $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        $.ajax({
            url : "{{url('admin/pole')}}"+"/"+id,
            type: "GET",
            data : {},
            success: function(data, textStatus, jqXHR)
            {
                if(textStatus == 'success'){
                    var users = '';
                    if(data.data.users.length > 0){
                      for(var i=0 ; i < data.data.users.length ;i++ ){
                        users += `<span class="badge badge-primary">`+data.data.users[i]+`</span>&nbsp;`;
                      }
                    }
                    else{
                        users += `<span class="badge badge-dark">No user</span>`;
                    }

                    console.log(users);
                    var d = new Date(data.data.pole.created_at);
                    var cur_date = d.toLocaleString();
                    var dialog = bootbox.dialog({
                        title: 'User Information',
                        buttons: {
                            cancel: {
                                label: '<i class="fa fa-times"></i> Cancel'
                            }
                        },
                        message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>'
                    });

                    dialog.init(function(){
                        setTimeout(function(){
                            dialog.find('.bootbox-body').html(`
                            <div class="form-group row">
                                <label for="inputId" class="col-sm-4 col-form-label">Identity</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control-plaintext" id="inputId"  readonly value="`+data.data.pole.identity+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputName" class="col-sm-4 col-form-label">NAME</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control-plaintext" id="inputName"  value="`+data.data.pole.name+`">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticIp" class="col-sm-4 col-form-label">Ip Address</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext"  value="`+data.data.pole.ip+`" >
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticLocation" class="col-sm-4 col-form-label">Location</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext"  value="`+data.data.pole.location+`" >
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticUsers" class="col-sm-4 col-form-label">Link Users</label>
                                <div class="col-sm-8">`+users+
                                `</div>
                            </div>
                            <div class="form-group row">
                                <label for="staticCreated" class="col-sm-4 col-form-label">CREATED DATE</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control-plaintext"  value="`+cur_date+`" >
                                </div>
                            </div>
                            `);
                        }, 500);
                    });
                }
                else{

                }
            },
            error: function (jqXHR, textStatus, errorThrown)
            {}
        });
    });

    @if(\Session::has('user_edit_success'))

        toastr.success('Success',"{{\Session::get('user_edit_success')}}",{
        showMethod: 'fadeIn',
        showDuration: 300,
        showEasing: 'swing',
        hideMethod: 'fadeOut',
        hideDuration: 1000,
        hideEasing: 'swing',
        extendedTimeOut: 1000,
        positionClass: 'toast-top-center',
        timeOut: 3000,
        escapeHtml: false,
        newestOnTop: true,
        preventDuplicates: false,
        progressBar: true
        });
    @endif
    @if(\Session::has('user_create_success'))
    toastr.success('Success',"{{\Session::get('user_create_success')}}",{
    showMethod: 'fadeIn',
    showDuration: 300,
    showEasing: 'swing',
    hideMethod: 'fadeOut',
    hideDuration: 1000,
    hideEasing: 'swing',
    extendedTimeOut: 1000,
    positionClass: 'toast-top-center',
    timeOut: 3000,
    escapeHtml: false,
    newestOnTop: true,
    preventDuplicates: false,
    progressBar: true
    });
    @endif
  });
</script>
@endsection